### ISSUE TITLE
MeetingBar

### ISSUE THREAD

**Issue by leits** [jamesjingyi/free-mac-apps#4]
https://github.com/leits/MeetingBar

I'm the author 😄

**Comment by jamesjingyi** [comment]
Hiya! Sorry I had surgery 2 weeks ago so was out of it for a little bit, but I'm back and taking an explore now! Sorry for the delay! Can I just check that the in-app purchases are just donations and don't unlock any other features?

I do like the app currently, and will test it for the next week. Thanks!

**Comment by leits** [comment]
Get well!

Yes, in-app purchases are just donations and don't unlock any other feature. Only show the nice "Thanks! You have supported MeetingBar for %d months 🎉" text.

Thanks!

**Comment by jamesjingyi** [comment]
Sorry for the super late reply, I have added MeetingBar, I particularly like:

- The ability to choose the browser or app different meeting types open in (when opening from MeetingBar)
- The ability to have MeetingBar automatically open a meeting
- The ability to quickly create a meeting from the menu bar
- The ability to customise the icon in the status bar
- The ability to customise the length of the event title
- The ability to customise the time 

Thanks again for your patience and for your great app, I really think it is a great app and I will be thoroughly recommending it!

I also wondered if I could make some very tiny suggestions:

1. If you turn on the Icon, the text looks out of line — I think the icon needs to be slightly shorter (see my screenshot where I line it up with the Control Centre icon) 
2. Just a tiny one, in Appearance > Status bar > Time, I think the dropdown shouldn't be 'show', instead it should say 'time to event' since this matches what you have above
![MeetingBar_Alignment](https://github.com/jamesjingyi/free-mac-apps/assets/25908161/75effdba-59e4-439f-85f9-c57f0be24f25)

Thanks again! I really appreciate you waiting

**Comment by leits** [comment]
Thanks @jamesjingyi!

I'll add your suggestions to the backlog 🙌
